# Generated by Django 4.1.3 on 2022-12-04 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatchResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatchTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterID1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character1', to='punkin_patch.character')),
                ('characterID2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character2', to='punkin_patch.character')),
                ('winningCharacterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winningCharacter', to='punkin_patch.character')),
            ],
        ),
        migrations.CreateModel(
            name='VotePatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patchResultsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punkin_patch.patchresults')),
                ('voteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punkin_patch.vote')),
            ],
        ),
        migrations.AddField(
            model_name='patchresults',
            name='patchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punkin_patch.patchtemplate'),
        ),
        migrations.CreateModel(
            name='CharacterPatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punkin_patch.character')),
                ('patchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punkin_patch.patchtemplate')),
            ],
        ),
        migrations.AddConstraint(
            model_name='votepatchresult',
            constraint=models.UniqueConstraint(fields=('voteID', 'patchResultsID'), name='No duplicate votes in patch results'),
        ),
        migrations.AddConstraint(
            model_name='characterpatch',
            constraint=models.UniqueConstraint(fields=('characterID', 'patchID'), name='One instance of character per patch'),
        ),
    ]
