# Generated by Django 4.1.3 on 2022-12-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punkin_patch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatchResults',
            new_name='PatchResult',
        ),
        migrations.RemoveConstraint(
            model_name='votepatchresult',
            name='No duplicate votes in patch results',
        ),
        migrations.RenameField(
            model_name='votepatchresult',
            old_name='patchResultsID',
            new_name='patchResultID',
        ),
        migrations.AddConstraint(
            model_name='votepatchresult',
            constraint=models.UniqueConstraint(fields=('voteID', 'patchResultID'), name='No duplicate votes in patch results'),
        ),
    ]
